// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use List;
use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DatamapList(Object<ffi::OsinfoDatamapList, ffi::OsinfoDatamapListClass>): List;

    match fn {
        get_type => || ffi::osinfo_datamaplist_get_type(),
    }
}

impl DatamapList {
    pub fn new() -> DatamapList {
        unsafe {
            from_glib_full(ffi::osinfo_datamaplist_new())
        }
    }
}

impl Default for DatamapList {
    fn default() -> Self {
        Self::new()
    }
}
