// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use Filter;
use List;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DeploymentList(Object<ffi::OsinfoDeploymentList, ffi::OsinfoDeploymentListClass>): List;

    match fn {
        get_type => || ffi::osinfo_deploymentlist_get_type(),
    }
}

impl DeploymentList {
    pub fn new() -> DeploymentList {
        unsafe {
            from_glib_full(ffi::osinfo_deploymentlist_new())
        }
    }
}

impl Default for DeploymentList {
    fn default() -> Self {
        Self::new()
    }
}

pub trait DeploymentListExt {
    fn new_copy(&self) -> Option<DeploymentList>;

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<DeploymentList>;

    fn new_intersection(&self, sourceTwo: &DeploymentList) -> Option<DeploymentList>;

    fn new_union(&self, sourceTwo: &DeploymentList) -> Option<DeploymentList>;
}

impl<O: IsA<DeploymentList>> DeploymentListExt for O {
    fn new_copy(&self) -> Option<DeploymentList> {
        unsafe {
            from_glib_full(ffi::osinfo_deploymentlist_new_copy(self.to_glib_none().0))
        }
    }

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<DeploymentList> {
        unsafe {
            from_glib_full(ffi::osinfo_deploymentlist_new_filtered(self.to_glib_none().0, filter.to_glib_none().0))
        }
    }

    fn new_intersection(&self, sourceTwo: &DeploymentList) -> Option<DeploymentList> {
        unsafe {
            from_glib_full(ffi::osinfo_deploymentlist_new_intersection(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }

    fn new_union(&self, sourceTwo: &DeploymentList) -> Option<DeploymentList> {
        unsafe {
            from_glib_full(ffi::osinfo_deploymentlist_new_union(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }
}
