// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use Device;
use Entity;
use ffi;
use glib;
use glib::object::Downcast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::boxed::Box as Box_;
use std::mem;
use std::mem::transmute;
use std::ptr;

glib_wrapper! {
    pub struct DeviceLink(Object<ffi::OsinfoDeviceLink, ffi::OsinfoDeviceLinkClass>): Entity;

    match fn {
        get_type => || ffi::osinfo_devicelink_get_type(),
    }
}

impl DeviceLink {
    pub fn new(target: &Device) -> DeviceLink {
        unsafe {
            from_glib_full(ffi::osinfo_devicelink_new(target.to_glib_none().0))
        }
    }
}

pub trait DeviceLinkExt {
    fn get_driver(&self) -> Option<String>;

    fn get_target(&self) -> Option<Device>;

    fn connect_property_target_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<DeviceLink> + IsA<glib::object::Object>> DeviceLinkExt for O {
    fn get_driver(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::osinfo_devicelink_get_driver(self.to_glib_none().0))
        }
    }

    fn get_target(&self) -> Option<Device> {
        unsafe {
            from_glib_none(ffi::osinfo_devicelink_get_target(self.to_glib_none().0))
        }
    }

    fn connect_property_target_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::target",
                transmute(notify_target_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}

unsafe extern "C" fn notify_target_trampoline<P>(this: *mut ffi::OsinfoDeviceLink, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<DeviceLink> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&DeviceLink::from_glib_borrow(this).downcast_unchecked())
}
