// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use Filter;
use List;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DeviceList(Object<ffi::OsinfoDeviceList, ffi::OsinfoDeviceListClass>): List;

    match fn {
        get_type => || ffi::osinfo_devicelist_get_type(),
    }
}

impl DeviceList {
    pub fn new() -> DeviceList {
        unsafe {
            from_glib_full(ffi::osinfo_devicelist_new())
        }
    }
}

impl Default for DeviceList {
    fn default() -> Self {
        Self::new()
    }
}

pub trait DeviceListExt {
    fn new_copy(&self) -> Option<DeviceList>;

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<DeviceList>;

    fn new_intersection(&self, sourceTwo: &DeviceList) -> Option<DeviceList>;

    fn new_union(&self, sourceTwo: &DeviceList) -> Option<DeviceList>;
}

impl<O: IsA<DeviceList>> DeviceListExt for O {
    fn new_copy(&self) -> Option<DeviceList> {
        unsafe {
            from_glib_full(ffi::osinfo_devicelist_new_copy(self.to_glib_none().0))
        }
    }

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<DeviceList> {
        unsafe {
            from_glib_full(ffi::osinfo_devicelist_new_filtered(self.to_glib_none().0, filter.to_glib_none().0))
        }
    }

    fn new_intersection(&self, sourceTwo: &DeviceList) -> Option<DeviceList> {
        unsafe {
            from_glib_full(ffi::osinfo_devicelist_new_intersection(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }

    fn new_union(&self, sourceTwo: &DeviceList) -> Option<DeviceList> {
        unsafe {
            from_glib_full(ffi::osinfo_devicelist_new_union(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }
}
