// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use List;
use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DeviceDriverList(Object<ffi::OsinfoDeviceDriverList, ffi::OsinfoDeviceDriverListClass>): List;

    match fn {
        get_type => || ffi::osinfo_device_driverlist_get_type(),
    }
}

impl DeviceDriverList {
    pub fn new() -> DeviceDriverList {
        unsafe {
            from_glib_full(ffi::osinfo_device_driverlist_new())
        }
    }
}

impl Default for DeviceDriverList {
    fn default() -> Self {
        Self::new()
    }
}
