// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use Filter;
use List;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct InstallScriptList(Object<ffi::OsinfoInstallScriptList, ffi::OsinfoInstallScriptListClass>): List;

    match fn {
        get_type => || ffi::osinfo_install_scriptlist_get_type(),
    }
}

impl InstallScriptList {
    pub fn new() -> InstallScriptList {
        unsafe {
            from_glib_full(ffi::osinfo_install_scriptlist_new())
        }
    }
}

impl Default for InstallScriptList {
    fn default() -> Self {
        Self::new()
    }
}

pub trait InstallScriptListExt {
    fn new_copy(&self) -> Option<InstallScriptList>;

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<InstallScriptList>;

    fn new_intersection(&self, sourceTwo: &InstallScriptList) -> Option<InstallScriptList>;

    fn new_union(&self, sourceTwo: &InstallScriptList) -> Option<InstallScriptList>;
}

impl<O: IsA<InstallScriptList>> InstallScriptListExt for O {
    fn new_copy(&self) -> Option<InstallScriptList> {
        unsafe {
            from_glib_full(ffi::osinfo_install_scriptlist_new_copy(self.to_glib_none().0))
        }
    }

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<InstallScriptList> {
        unsafe {
            from_glib_full(ffi::osinfo_install_scriptlist_new_filtered(self.to_glib_none().0, filter.to_glib_none().0))
        }
    }

    fn new_intersection(&self, sourceTwo: &InstallScriptList) -> Option<InstallScriptList> {
        unsafe {
            from_glib_full(ffi::osinfo_install_scriptlist_new_intersection(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }

    fn new_union(&self, sourceTwo: &InstallScriptList) -> Option<InstallScriptList> {
        unsafe {
            from_glib_full(ffi::osinfo_install_scriptlist_new_union(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }
}
