// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use Entity;
use Error;
use Os;
use OsVariantList;
use ffi;
use gio;
use glib;
use glib::Value;
use glib::object::Downcast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::boxed::Box as Box_;
use std::mem;
use std::mem::transmute;
use std::ptr;

glib_wrapper! {
    pub struct Media(Object<ffi::OsinfoMedia, ffi::OsinfoMediaClass>): Entity;

    match fn {
        get_type => || ffi::osinfo_media_get_type(),
    }
}

impl Media {
    pub fn new(id: &str, architecture: &str) -> Media {
        unsafe {
            from_glib_full(ffi::osinfo_media_new(id.to_glib_none().0, architecture.to_glib_none().0))
        }
    }

    pub fn create_from_location<'a, P: Into<Option<&'a gio::Cancellable>>>(location: &str, cancellable: P) -> Result<Media, Error> {
        let cancellable = cancellable.into();
        let cancellable = cancellable.to_glib_none();
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::osinfo_media_create_from_location(location.to_glib_none().0, cancellable.0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    //pub fn create_from_location_async<'a, 'b, P: Into<Option<&'a gio::Cancellable>>, Q: Into<Option<&'b /*Ignored*/gio::AsyncReadyCallback>>, R: Into<Option</*Unimplemented*/Fundamental: Pointer>>>(location: &str, priority: i32, cancellable: P, callback: Q, user_data: R) {
    //    unsafe { TODO: call ffi::osinfo_media_create_from_location_async() }
    //}

    //pub fn create_from_location_finish<P: IsA</*Ignored*/gio::AsyncResult>>(res: &P) -> Result<Media, Error> {
    //    unsafe { TODO: call ffi::osinfo_media_create_from_location_finish() }
    //}
}

pub trait MediaExt {
    fn get_application_id(&self) -> Option<String>;

    fn get_architecture(&self) -> Option<String>;

    fn get_eject_after_install(&self) -> bool;

    fn get_initrd_path(&self) -> Option<String>;

    fn get_installer(&self) -> bool;

    fn get_installer_reboots(&self) -> i32;

    fn get_kernel_path(&self) -> Option<String>;

    fn get_languages(&self) -> Vec<String>;

    fn get_live(&self) -> bool;

    fn get_os(&self) -> Option<Os>;

    fn get_os_variants(&self) -> Option<OsVariantList>;

    fn get_publisher_id(&self) -> Option<String>;

    fn get_system_id(&self) -> Option<String>;

    fn get_url(&self) -> Option<String>;

    fn get_volume_id(&self) -> Option<String>;

    fn get_volume_size(&self) -> i64;

    fn set_property_application_id(&self, application_id: Option<&str>);

    fn set_property_architecture(&self, architecture: Option<&str>);

    fn set_property_eject_after_install(&self, eject_after_install: bool);

    fn set_property_initrd_path(&self, initrd_path: Option<&str>);

    fn set_property_installer(&self, installer: bool);

    fn set_property_installer_reboots(&self, installer_reboots: i32);

    fn set_property_kernel_path(&self, kernel_path: Option<&str>);

    fn set_property_live(&self, live: bool);

    fn set_property_os(&self, os: Option<&Os>);

    fn set_property_publisher_id(&self, publisher_id: Option<&str>);

    fn set_property_system_id(&self, system_id: Option<&str>);

    fn set_property_url(&self, url: Option<&str>);

    fn set_property_volume_id(&self, volume_id: Option<&str>);

    fn set_property_volume_size(&self, volume_size: i64);

    fn connect_property_application_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_architecture_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_eject_after_install_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_initrd_path_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_installer_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_installer_reboots_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_kernel_path_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_languages_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_live_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_os_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_publisher_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_system_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_url_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_volume_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_volume_size_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<Media> + IsA<glib::object::Object>> MediaExt for O {
    fn get_application_id(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::osinfo_media_get_application_id(self.to_glib_none().0))
        }
    }

    fn get_architecture(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::osinfo_media_get_architecture(self.to_glib_none().0))
        }
    }

    fn get_eject_after_install(&self) -> bool {
        unsafe {
            from_glib(ffi::osinfo_media_get_eject_after_install(self.to_glib_none().0))
        }
    }

    fn get_initrd_path(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::osinfo_media_get_initrd_path(self.to_glib_none().0))
        }
    }

    fn get_installer(&self) -> bool {
        unsafe {
            from_glib(ffi::osinfo_media_get_installer(self.to_glib_none().0))
        }
    }

    fn get_installer_reboots(&self) -> i32 {
        unsafe {
            ffi::osinfo_media_get_installer_reboots(self.to_glib_none().0)
        }
    }

    fn get_kernel_path(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::osinfo_media_get_kernel_path(self.to_glib_none().0))
        }
    }

    fn get_languages(&self) -> Vec<String> {
        unsafe {
            FromGlibPtrContainer::from_glib_container(ffi::osinfo_media_get_languages(self.to_glib_none().0))
        }
    }

    fn get_live(&self) -> bool {
        unsafe {
            from_glib(ffi::osinfo_media_get_live(self.to_glib_none().0))
        }
    }

    fn get_os(&self) -> Option<Os> {
        unsafe {
            from_glib_full(ffi::osinfo_media_get_os(self.to_glib_none().0))
        }
    }

    fn get_os_variants(&self) -> Option<OsVariantList> {
        unsafe {
            from_glib_full(ffi::osinfo_media_get_os_variants(self.to_glib_none().0))
        }
    }

    fn get_publisher_id(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::osinfo_media_get_publisher_id(self.to_glib_none().0))
        }
    }

    fn get_system_id(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::osinfo_media_get_system_id(self.to_glib_none().0))
        }
    }

    fn get_url(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::osinfo_media_get_url(self.to_glib_none().0))
        }
    }

    fn get_volume_id(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::osinfo_media_get_volume_id(self.to_glib_none().0))
        }
    }

    fn get_volume_size(&self) -> i64 {
        unsafe {
            ffi::osinfo_media_get_volume_size(self.to_glib_none().0)
        }
    }

    fn set_property_application_id(&self, application_id: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "application-id".to_glib_none().0, Value::from(application_id).to_glib_none().0);
        }
    }

    fn set_property_architecture(&self, architecture: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "architecture".to_glib_none().0, Value::from(architecture).to_glib_none().0);
        }
    }

    fn set_property_eject_after_install(&self, eject_after_install: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "eject-after-install".to_glib_none().0, Value::from(&eject_after_install).to_glib_none().0);
        }
    }

    fn set_property_initrd_path(&self, initrd_path: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "initrd-path".to_glib_none().0, Value::from(initrd_path).to_glib_none().0);
        }
    }

    fn set_property_installer(&self, installer: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "installer".to_glib_none().0, Value::from(&installer).to_glib_none().0);
        }
    }

    fn set_property_installer_reboots(&self, installer_reboots: i32) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "installer-reboots".to_glib_none().0, Value::from(&installer_reboots).to_glib_none().0);
        }
    }

    fn set_property_kernel_path(&self, kernel_path: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "kernel-path".to_glib_none().0, Value::from(kernel_path).to_glib_none().0);
        }
    }

    fn set_property_live(&self, live: bool) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "live".to_glib_none().0, Value::from(&live).to_glib_none().0);
        }
    }

    fn set_property_os(&self, os: Option<&Os>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "os".to_glib_none().0, Value::from(os).to_glib_none().0);
        }
    }

    fn set_property_publisher_id(&self, publisher_id: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "publisher-id".to_glib_none().0, Value::from(publisher_id).to_glib_none().0);
        }
    }

    fn set_property_system_id(&self, system_id: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "system-id".to_glib_none().0, Value::from(system_id).to_glib_none().0);
        }
    }

    fn set_property_url(&self, url: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "url".to_glib_none().0, Value::from(url).to_glib_none().0);
        }
    }

    fn set_property_volume_id(&self, volume_id: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "volume-id".to_glib_none().0, Value::from(volume_id).to_glib_none().0);
        }
    }

    fn set_property_volume_size(&self, volume_size: i64) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "volume-size".to_glib_none().0, Value::from(&volume_size).to_glib_none().0);
        }
    }

    fn connect_property_application_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::application-id",
                transmute(notify_application_id_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_architecture_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::architecture",
                transmute(notify_architecture_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_eject_after_install_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::eject-after-install",
                transmute(notify_eject_after_install_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_initrd_path_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::initrd-path",
                transmute(notify_initrd_path_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_installer_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::installer",
                transmute(notify_installer_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_installer_reboots_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::installer-reboots",
                transmute(notify_installer_reboots_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_kernel_path_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::kernel-path",
                transmute(notify_kernel_path_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_languages_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::languages",
                transmute(notify_languages_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_live_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::live",
                transmute(notify_live_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_os_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::os",
                transmute(notify_os_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_publisher_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::publisher-id",
                transmute(notify_publisher_id_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_system_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::system-id",
                transmute(notify_system_id_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_url_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::url",
                transmute(notify_url_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_volume_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::volume-id",
                transmute(notify_volume_id_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_volume_size_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::volume-size",
                transmute(notify_volume_size_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}

unsafe extern "C" fn notify_application_id_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_architecture_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_eject_after_install_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_initrd_path_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_installer_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_installer_reboots_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_kernel_path_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_languages_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_live_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_os_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_publisher_id_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_system_id_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_url_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_volume_id_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_volume_size_trampoline<P>(this: *mut ffi::OsinfoMedia, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<Media> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&Media::from_glib_borrow(this).downcast_unchecked())
}
