// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use Entity;
use ffi;
use glib;
use glib::Value;
use glib::object::Downcast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::boxed::Box as Box_;
use std::mem;
use std::mem::transmute;
use std::ptr;

glib_wrapper! {
    pub struct OsVariant(Object<ffi::OsinfoOsVariant, ffi::OsinfoOsVariantClass>): Entity;

    match fn {
        get_type => || ffi::osinfo_os_variant_get_type(),
    }
}

impl OsVariant {
    pub fn new(id: &str) -> OsVariant {
        unsafe {
            from_glib_full(ffi::osinfo_os_variant_new(id.to_glib_none().0))
        }
    }
}

pub trait OsVariantExt {
    fn get_name(&self) -> Option<String>;

    fn set_property_name(&self, name: Option<&str>);

    fn connect_property_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<OsVariant> + IsA<glib::object::Object>> OsVariantExt for O {
    fn get_name(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::osinfo_os_variant_get_name(self.to_glib_none().0))
        }
    }

    fn set_property_name(&self, name: Option<&str>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "name".to_glib_none().0, Value::from(name).to_glib_none().0);
        }
    }

    fn connect_property_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::name",
                transmute(notify_name_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}

unsafe extern "C" fn notify_name_trampoline<P>(this: *mut ffi::OsinfoOsVariant, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<OsVariant> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&OsVariant::from_glib_borrow(this).downcast_unchecked())
}
