// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use Filter;
use List;
use ProductList;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct PlatformList(Object<ffi::OsinfoPlatformList, ffi::OsinfoPlatformListClass>): ProductList, List;

    match fn {
        get_type => || ffi::osinfo_platformlist_get_type(),
    }
}

impl PlatformList {
    pub fn new() -> PlatformList {
        unsafe {
            from_glib_full(ffi::osinfo_platformlist_new())
        }
    }
}

impl Default for PlatformList {
    fn default() -> Self {
        Self::new()
    }
}

pub trait PlatformListExt {
    fn new_copy(&self) -> Option<PlatformList>;

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<PlatformList>;

    fn new_intersection(&self, sourceTwo: &PlatformList) -> Option<PlatformList>;

    fn new_union(&self, sourceTwo: &PlatformList) -> Option<PlatformList>;
}

impl<O: IsA<PlatformList>> PlatformListExt for O {
    fn new_copy(&self) -> Option<PlatformList> {
        unsafe {
            from_glib_full(ffi::osinfo_platformlist_new_copy(self.to_glib_none().0))
        }
    }

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<PlatformList> {
        unsafe {
            from_glib_full(ffi::osinfo_platformlist_new_filtered(self.to_glib_none().0, filter.to_glib_none().0))
        }
    }

    fn new_intersection(&self, sourceTwo: &PlatformList) -> Option<PlatformList> {
        unsafe {
            from_glib_full(ffi::osinfo_platformlist_new_intersection(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }

    fn new_union(&self, sourceTwo: &PlatformList) -> Option<PlatformList> {
        unsafe {
            from_glib_full(ffi::osinfo_platformlist_new_union(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }
}
