// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use Filter;
use List;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct ResourcesList(Object<ffi::OsinfoResourcesList, ffi::OsinfoResourcesListClass>): List;

    match fn {
        get_type => || ffi::osinfo_resourceslist_get_type(),
    }
}

impl ResourcesList {
    pub fn new() -> ResourcesList {
        unsafe {
            from_glib_full(ffi::osinfo_resourceslist_new())
        }
    }
}

impl Default for ResourcesList {
    fn default() -> Self {
        Self::new()
    }
}

pub trait ResourcesListExt {
    fn new_copy(&self) -> Option<ResourcesList>;

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<ResourcesList>;

    fn new_intersection(&self, sourceTwo: &ResourcesList) -> Option<ResourcesList>;

    fn new_union(&self, sourceTwo: &ResourcesList) -> Option<ResourcesList>;
}

impl<O: IsA<ResourcesList>> ResourcesListExt for O {
    fn new_copy(&self) -> Option<ResourcesList> {
        unsafe {
            from_glib_full(ffi::osinfo_resourceslist_new_copy(self.to_glib_none().0))
        }
    }

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<ResourcesList> {
        unsafe {
            from_glib_full(ffi::osinfo_resourceslist_new_filtered(self.to_glib_none().0, filter.to_glib_none().0))
        }
    }

    fn new_intersection(&self, sourceTwo: &ResourcesList) -> Option<ResourcesList> {
        unsafe {
            from_glib_full(ffi::osinfo_resourceslist_new_intersection(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }

    fn new_union(&self, sourceTwo: &ResourcesList) -> Option<ResourcesList> {
        unsafe {
            from_glib_full(ffi::osinfo_resourceslist_new_union(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }
}
