// This file was generated by gir (0409d73) from gir-files (???)
// DO NOT EDIT

use Filter;
use List;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct TreeList(Object<ffi::OsinfoTreeList, ffi::OsinfoTreeListClass>): List;

    match fn {
        get_type => || ffi::osinfo_treelist_get_type(),
    }
}

impl TreeList {
    pub fn new() -> TreeList {
        unsafe {
            from_glib_full(ffi::osinfo_treelist_new())
        }
    }
}

impl Default for TreeList {
    fn default() -> Self {
        Self::new()
    }
}

pub trait TreeListExt {
    fn new_copy(&self) -> Option<TreeList>;

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<TreeList>;

    fn new_intersection(&self, sourceTwo: &TreeList) -> Option<TreeList>;

    fn new_union(&self, sourceTwo: &TreeList) -> Option<TreeList>;
}

impl<O: IsA<TreeList>> TreeListExt for O {
    fn new_copy(&self) -> Option<TreeList> {
        unsafe {
            from_glib_full(ffi::osinfo_treelist_new_copy(self.to_glib_none().0))
        }
    }

    fn new_filtered<P: IsA<Filter>>(&self, filter: &P) -> Option<TreeList> {
        unsafe {
            from_glib_full(ffi::osinfo_treelist_new_filtered(self.to_glib_none().0, filter.to_glib_none().0))
        }
    }

    fn new_intersection(&self, sourceTwo: &TreeList) -> Option<TreeList> {
        unsafe {
            from_glib_full(ffi::osinfo_treelist_new_intersection(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }

    fn new_union(&self, sourceTwo: &TreeList) -> Option<TreeList> {
        unsafe {
            from_glib_full(ffi::osinfo_treelist_new_union(self.to_glib_none().0, sourceTwo.to_glib_none().0))
        }
    }
}
